import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Auth
      'login': 'Login',
      'register': 'Register',
      'welcome_back': 'Welcome Back',
      'login_to_rider_account': 'Login to your rider account',
      'phone_number': 'Phone Number',
      'phone_hint': '612345678',
      'enter_phone': 'Please enter your phone number',
      'include_country_code': 'Include country code (e.g. +222)',
      'resend': 'Resend',
      'send_otp': 'Send OTP',
      'otp_sent_success': 'OTP sent successfully',
      'failed_send_otp': 'Failed to send OTP',
      'enter_otp': 'Enter OTP',
      'otp_hint': 'Enter the OTP sent to your phone',
      'please_enter_otp': 'Please enter the OTP',
      'login_failed': 'Login failed',
      'no_account_register': "Don't have an account? Register",
      'register_as_rider': 'Register as Rider',
      'personal_info': 'Personal Info',
      'full_name': 'Full Name',
      'enter_name': 'Enter your full name',
      'required': 'Required',
      'password': 'Password',
      'enter_password': 'Enter your password',
      'min_6_chars': 'Min 6 characters',
      'driving_licence': 'Driving Licence',
      'licence_number': 'Licence Number',
      'enter_licence': 'Enter your driving licence number',
      'vehicle_type': 'Vehicle Type',
      'bike': 'Bike',
      'scooter': 'Scooter',
      'car': 'Car',
      'upload_licence_image': 'Upload Driving Licence Image',
      'tap_to_upload': 'Tap to take photo or choose from gallery',
      'send_otp_continue': 'Send OTP & Continue',
      'already_have_account_login': 'Already have an account? Login',
      'please_upload_licence': 'Please upload your driving licence image',
      'take_photo': 'Take Photo',
      'choose_from_gallery': 'Choose from Gallery',
      'verify_phone': 'Verify Phone',
      'verify_your_phone': 'Verify Your Phone',
      'sent_code_to': 'We sent a 6-digit code to',
      'verify_register': 'Verify & Register',
      'didnt_receive_code': "Didn't receive code?",
      'resend_in': 'Resend in',
      'registration_submitted': 'Registration Submitted!',
      'rider_under_review': 'Your rider registration is under review by our admin team.',
      'approval_time': 'Approval takes 24 to 48 hours.',
      'ok_got_it': 'OK, Got it',
      'enter_6_digit_otp': 'Please enter the 6-digit OTP',
      'something_went_wrong': 'Something went wrong',
      'waiting_admin_approval': 'Waiting for Admin Approval',
      'rider_submitted_desc': 'Your rider registration has been submitted. Our admin team will review your details and driving licence.',
      'approval_takes_time': 'Approval typically takes 24 to 48 hours.',
      'check_status': 'Check Status',
      'checking': 'Checking...',
      'still_pending': 'Still pending approval. Please wait.',
      'application_rejected': 'Application Rejected',
      'rider_rejected_desc': 'Unfortunately, your rider registration was not approved by the admin.',
      'admin_note': 'Admin Note',
      'try_again': 'Try Again',

      // Profile
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'wallet': 'Wallet',
      'privacy_policy': 'Privacy Policy',
      'change_password': 'Change Password',
      'help_support': 'Help & Support',
      'logout': 'Logout',
      'language': 'Language',
      'select_language': 'Select Language',
      'english': 'English',
      'french': 'French',
      'arabic': 'Arabic',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'logout_confirm': 'Are you sure you want to logout?',
      'delete_account': 'Delete Account',
      'delete': 'Delete',
      'delete_account_confirm': 'This will permanently delete your account and all your data. This action cannot be undone. Are you sure?',
      'account_deleted': 'Your account has been deleted',
      'delete_account_failed': 'Failed to delete account',
      'rider': 'Rider',
      'payment': 'Payment',
      'pickup_for': 'Pickup for',
      'accept_delivery': 'Accept Delivery',
      'order': 'Order',
      'distance': 'Distance',

      // Navigation & Dashboard
      'deliveries': 'Deliveries',
      'history': 'History',
      'new_tasks': 'New Tasks',
      'active_tasks': 'Active Tasks',
      'completed_tasks': 'Completed Tasks',
      'earnings': 'Earnings',
      'ready_to_earn': 'Ready to earn today?',
      'today_earnings': 'Today\'s Earnings',
      'today_deliveries': 'Today\'s Deliveries',
      'online': 'Online',
      'offline': 'Offline',
      'available_orders': 'Available Orders',
      'mad': 'MRO',
      'accept': 'Accept',
      'skip': 'Skip',
      'location_required': 'Location permission required to receive nearby orders. Tap to enable.',
      'availability': 'Availability',
      'request_payout': 'Request Payout',
      'you_are_offline': 'You\'re offline',
      'toggle_availability_desc': 'Toggle your availability to start receiving job offers',
      'no_jobs_nearby': 'No jobs available nearby',
      'new_jobs_desc': 'New jobs will appear here automatically',
      'no_orders_nearby': 'No orders nearby',
      'pull_to_refresh_desc': 'Pull to refresh or wait for new orders',
      'delivery_details': 'Delivery Details',
      'order_information': 'Order Information',
      'locations': 'Locations',
      'delivery_fee': 'Delivery Fee',
      'delivery_accepted': 'Delivery accepted!',
      'failed_to_accept': 'Failed to accept delivery',
      'head_to_pharmacy': 'Head to Pharmacy',
      'head_to_patient': 'Head to Patient',
      'delivery_complete': 'Delivery Complete!',
      'complete_delivery_before_back': 'Complete the delivery before going back',
      'pickup_location': 'Pickup Location',
      'delivery_location': 'Delivery Location',
      'then_deliver_to': 'Then Deliver To',
      'completed': 'Completed',
      'delivery_done': 'Delivery done',
      'arrived_at_pharmacy': 'Arrived at Pharmacy',
      'arrived_at_patient': 'Arrived at Patient',
      'you_earned': 'You earned',
      'back_to_home': 'Back to Home',
      
      // Tasks
      'order_id': 'Order ID',
      'pickup': 'Pickup',
      'delivery': 'Delivery',
      'accept_task': 'Accept Task',
      'reject_task': 'Reject Task',
      'start_pickup': 'Start Pickup',
      'mark_picked_up': 'Mark as Picked Up',
      'start_delivery': 'Start Delivery',
      'mark_delivered': 'Mark as Delivered',
      'view_on_map': 'View on Map',
      'call_customer': 'Call Customer',
      'call_pharmacy': 'Call Pharmacy',
      
      // General
      'status': 'Status',
      'pending': 'Pending',
      'on_way': 'On the Way',
      'delivered': 'Delivered',
      'cancelled': 'Cancelled',
    },
    'fr': {
      // Auth
      'login': 'Connexion',
      'register': 'S\'inscrire',
      'welcome_back': 'Bon retour',
      'login_to_rider_account': 'Connectez-vous à votre compte livreur',
      'phone_number': 'Numéro de téléphone',
      'phone_hint': '612345678',
      'enter_phone': 'Veuillez entrer votre numéro de téléphone',
      'include_country_code': 'Inclure le code pays (ex: +222)',
      'resend': 'Renvoyer',
      'send_otp': 'Envoyer l\'OTP',
      'otp_sent_success': 'OTP envoyé avec succès',
      'failed_send_otp': 'Échec de l\'envoi de l\'OTP',
      'enter_otp': 'Entrer l\'OTP',
      'otp_hint': 'Entrez l\'OTP envoyé à votre téléphone',
      'please_enter_otp': 'Veuillez entrer l\'OTP',
      'login_failed': 'Échec de la connexion',
      'no_account_register': 'Pas de compte ? S\'inscrire',
      'register_as_rider': 'S\'inscrire en tant que livreur',
      'personal_info': 'Informations personnelles',
      'full_name': 'Nom complet',
      'enter_name': 'Entrez votre nom complet',
      'required': 'Requis',
      'password': 'Mot de passe',
      'enter_password': 'Entrez votre mot de passe',
      'min_6_chars': 'Min 6 caractères',
      'driving_licence': 'Permis de conduire',
      'licence_number': 'Numéro de permis',
      'enter_licence': 'Entrez votre numéro de permis de conduire',
      'vehicle_type': 'Type de véhicule',
      'bike': 'Vélo',
      'scooter': 'Scooter',
      'car': 'Voiture',
      'upload_licence_image': 'Télécharger l\'image du permis',
      'tap_to_upload': 'Appuyez pour prendre une photo ou choisir dans la galerie',
      'send_otp_continue': 'Envoyer l\'OTP et continuer',
      'already_have_account_login': 'Déjà un compte ? Se connecter',
      'please_upload_licence': 'Veuillez télécharger l\'image de votre permis',
      'take_photo': 'Prendre une photo',
      'choose_from_gallery': 'Choisir dans la galerie',
      'verify_phone': 'Vérifier le téléphone',
      'verify_your_phone': 'Vérifiez votre téléphone',
      'sent_code_to': 'Nous avons envoyé un code à 6 chiffres à',
      'verify_register': 'Vérifier et s\'inscrire',
      'didnt_receive_code': 'Pas reçu le code ?',
      'resend_in': 'Renvoyer dans',
      'registration_submitted': 'Inscription soumise !',
      'rider_under_review': 'Votre inscription de livreur est en cours de révision par notre équipe.',
      'approval_time': 'L\'approbation prend 24 à 48 heures.',
      'ok_got_it': 'OK, j\'ai compris',
      'enter_6_digit_otp': 'Veuillez entrer le code à 6 chiffres',
      'something_went_wrong': 'Quelque chose s\'est mal passé',
      'waiting_admin_approval': 'En attente d\'approbation',
      'rider_submitted_desc': 'Votre inscription a été soumise. Notre équipe examinera vos détails et votre permis.',
      'approval_takes_time': 'L\'approbation prend généralement 24 à 48 heures.',
      'check_status': 'Vérifier le statut',
      'checking': 'Vérification...',
      'still_pending': 'Toujours en attente d\'approbation. Veuillez patienter.',
      'application_rejected': 'Demande rejetée',
      'rider_rejected_desc': 'Malheureusement, votre inscription n\'a pas été approuvée.',
      'admin_note': 'Note de l\'admin',
      'try_again': 'Réessayer',

      // Profile
      'profile': 'Profil',
      'edit_profile': 'Modifier le profil',
      'wallet': 'Portefeuille',
      'privacy_policy': 'Politique de confidentialité',
      'change_password': 'Modifier le mot de passe',
      'help_support': 'Aide et support',
      'logout': 'Déconnexion',
      'language': 'Langue',
      'select_language': 'Choisir la langue',
      'english': 'Anglais',
      'french': 'Français',
      'arabic': 'Arabe',
      'confirm': 'Confirmer',
      'cancel': 'Annuler',
      'logout_confirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
      'delete_account': 'Supprimer le compte',
      'delete': 'Supprimer',
      'delete_account_confirm': 'Cela supprimera définitivement votre compte et toutes vos données. Cette action est irréversible. Êtes-vous sûr ?',
      'account_deleted': 'Votre compte a été supprimé',
      'delete_account_failed': 'Échec de la suppression du compte',
      'rider': 'Livreur',
      'payment': 'Paiement',
      'pickup_for': 'Ramassage pour',
      'accept_delivery': 'Accepter la livraison',
      'order': 'Commande',
      'distance': 'Distance',

      // Navigation & Dashboard
      'deliveries': 'Livraisons',
      'history': 'Historique',
      'new_tasks': 'Nouvelles tâches',
      'active_tasks': 'Tâches actives',
      'completed_tasks': 'Tâches terminées',
      'earnings': 'Gains',
      'ready_to_earn': 'Prêt à gagner aujourd\'hui ?',
      'today_earnings': 'Gains du jour',
      'today_deliveries': 'Livraisons du jour',
      'online': 'En ligne',
      'offline': 'Hors ligne',
      'available_orders': 'Commandes disponibles',
      'mad': 'MRO',
      'accept': 'Accepter',
      'skip': 'Passer',
      'location_required': 'Autorisation de localisation requise pour recevoir des commandes à proximité. Appuyez pour activer.',
      'availability': 'Disponibilité',
      'request_payout': 'Demander le paiement',
      'you_are_offline': 'Vous êtes hors ligne',
      'toggle_availability_desc': 'Basculez votre disponibilité pour commencer à recevoir des offres d\'emploi',
      'no_jobs_nearby': 'Aucun travail disponible à proximité',
      'new_jobs_desc': 'Les nouveaux travaux apparaîtront ici automatiquement',
      'no_orders_nearby': 'Aucune commande à proximité',
      'pull_to_refresh_desc': 'Tirez pour rafraîchir ou attendez de nouvelles commandes',
      'delivery_details': 'Détails de la livraison',
      'order_information': 'Informations sur la commande',
      'locations': 'Lieux',
      'delivery_fee': 'Frais de livraison',
      'delivery_accepted': 'Livraison acceptée !',
      'failed_to_accept': 'Échec de l\'acceptation de la livraison',
      'head_to_pharmacy': 'Allez à la pharmacie',
      'head_to_patient': 'Allez chez le patient',
      'delivery_complete': 'Livraison terminée !',
      'complete_delivery_before_back': 'Terminez la livraison avant de revenir en arrière',
      'pickup_location': 'Lieu de ramassage',
      'delivery_location': 'Lieu de livraison',
      'then_deliver_to': 'Ensuite, livrez à',
      'completed': 'Terminé',
      'delivery_done': 'Livraison effectuée',
      'arrived_at_pharmacy': 'Arrivé à la pharmacie',
      'arrived_at_patient': 'Arrivé chez le patient',
      'you_earned': 'Vous avez gagné',
      'back_to_home': 'Retour à l\'accueil',
      
      // Tasks
      'order_id': 'ID de commande',
      'pickup': 'Ramassage',
      'delivery': 'Livraison',
      'accept_task': 'Accepter la tâche',
      'reject_task': 'Rejeter la tâche',
      'start_pickup': 'Commencer le ramassage',
      'mark_picked_up': 'Marquer comme récupéré',
      'start_delivery': 'Commencer la livraison',
      'mark_delivered': 'Marquer comme livré',
      'view_on_map': 'Voir sur la carte',
      'call_customer': 'Appeler le client',
      'call_pharmacy': 'Appeler la pharmacie',
      
      // General
      'status': 'Statut',
      'pending': 'En attente',
      'on_way': 'En chemin',
      'delivered': 'Livré',
      'cancelled': 'Annulé',
    },
    'ar': {
      // Auth
      'login': 'تسجيل الدخول',
      'register': 'تسجيل',
      'welcome_back': 'مرحباً بك',
      'login_to_rider_account': 'تسجيل الدخول إلى حساب السائق الخاص بك',
      'phone_number': 'رقم الهاتف',
      'phone_hint': '612345678',
      'enter_phone': 'يرجى إدخال رقم هاتفك',
      'include_country_code': 'تضمين رمز الدولة (مثال: +222)',
      'resend': 'إعادة إرسال',
      'send_otp': 'إرسال رمز التحقق',
      'otp_sent_success': 'تم إرسال رمز التحقق بنجاح',
      'failed_send_otp': 'فشل إرسال رمز التحقق',
      'enter_otp': 'أدخل رمز التحقق',
      'otp_hint': 'أدخل رمز التحقق المرسل إلى هاتفك',
      'please_enter_otp': 'يرجى إدخال رمز التحقق',
      'login_failed': 'فشل تسجيل الدخول',
      'no_account_register': 'ليس لديك حساب؟ سجل الآن',
      'register_as_rider': 'التسجيل كسائق',
      'personal_info': 'المعلومات الشخصية',
      'full_name': 'الاسم الكامل',
      'enter_name': 'أدخل اسمك الكامل',
      'required': 'مطلوب',
      'password': 'كلمة المرور',
      'enter_password': 'أدخل كلمة المرور الخاصة بك',
      'min_6_chars': '6 أحرف على الأقل',
      'driving_licence': 'رخصة القيادة',
      'licence_number': 'رقم الرخصة',
      'enter_licence': 'أدخل رقم رخصة القيادة الخاصة بك',
      'vehicle_type': 'نوع المركبة',
      'bike': 'دراجة',
      'scooter': 'سكوتر',
      'car': 'سيارة',
      'upload_licence_image': 'تحميل صورة رخصة القيادة',
      'tap_to_upload': 'اضغط لالتقاط صورة أو اختر من المعرض',
      'send_otp_continue': 'إرسال رمز التحقق والمتابعة',
      'already_have_account_login': 'لديك حساب بالفعل؟ تسجيل الدخول',
      'please_upload_licence': 'يرجى تحميل صورة رخصة القيادة الخاصة بك',
      'take_photo': 'التقاط صورة',
      'choose_from_gallery': 'اختيار من المعرض',
      'verify_phone': 'تأكيد الهاتف',
      'verify_your_phone': 'أكد رقم هاتفك',
      'sent_code_to': 'لقد أرسلنا رمزاً مكوناً من 6 أرقام إلى',
      'verify_register': 'تأكيد وتسجيل',
      'didnt_receive_code': 'لم يصلك الرمز؟',
      'resend_in': 'إعادة الإرسال خلال',
      'registration_submitted': 'تم تقديم الطلب!',
      'rider_under_review': 'طلب التسجيل الخاص بك قيد المراجعة من قبل فريقنا.',
      'approval_time': 'الموافقة تستغرق من 24 إلى 48 ساعة.',
      'ok_got_it': 'حسناً، فهمت',
      'enter_6_digit_otp': 'يرجى إدخال الرمز المكون من 6 أرقام',
      'something_went_wrong': 'حدث خطأ ما',
      'waiting_admin_approval': 'في انتظار موافقة المسؤول',
      'rider_submitted_desc': 'تم تقديم طلبك. سيقوم فريقنا بمراجعة بياناتك ورخصة القيادة.',
      'approval_takes_time': 'تستغرق الموافقة عادةً من 24 إلى 48 ساعة.',
      'check_status': 'التحقق من الحالة',
      'checking': 'جاري التحقق...',
      'still_pending': 'لا يزال الطلب قيد المراجعة. يرجى الانتظار.',
      'application_rejected': 'تم رفض الطلب',
      'rider_rejected_desc': 'للأسف، لم يتمت الموافقة على طلب التسجيل الخاص بك.',
      'admin_note': 'ملاحظة المسؤول',
      'try_again': 'حاول مرة أخرى',

      // Profile
      'profile': 'الملف الشخصي',
      'edit_profile': 'تعديل الملف الشخصي',
      'wallet': 'المحفظة',
      'privacy_policy': 'سياسة الخصوصية',
      'change_password': 'تغيير كلمة المرور',
      'help_support': 'المساعدة والدعم',
      'logout': 'تسجيل الخروج',
      'language': 'اللغة',
      'select_language': 'اختر اللغة',
      'english': 'الإنجليزية',
      'french': 'الفرنسية',
      'arabic': 'العربية',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'logout_confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'delete_account': 'حذف الحساب',
      'delete': 'حذف',
      'delete_account_confirm': 'سيؤدي هذا إلى حذف حسابك وجميع بياناتك نهائيًا. لا يمكن التراجع عن هذا الإجراء. هل أنت متأكد؟',
      'account_deleted': 'تم حذف حسابك',
      'delete_account_failed': 'فشل حذف الحساب',
      'rider': 'سائق',
      'payment': 'الدفع',
      'pickup_for': 'استلام لـ',
      'accept_delivery': 'قبول التوصيل',
      'order': 'طلب',
      'distance': 'المسافة',

      // Navigation & Dashboard
      'deliveries': 'التوصيلات',
      'history': 'السجل',
      'new_tasks': 'مهام جديدة',
      'active_tasks': 'المهام النشطة',
      'completed_tasks': 'المهام المكتملة',
      'earnings': 'الأرباح',
      'ready_to_earn': 'هل أنت مستعد للربح اليوم؟',
      'today_earnings': 'أرباح اليوم',
      'today_deliveries': 'توصيلات اليوم',
      'online': 'متصل',
      'offline': 'غير متصل',
      'available_orders': 'الطلبات المتاحة',
      'mad': 'أوقية',
      'accept': 'قبول',
      'skip': 'تخطي',
      'location_required': 'مطلوب إذن الموقع لتلقي الطلبات القريبة. اضغط للتفعيل.',
      'availability': 'التوفر',
      'request_payout': 'طلب الدفع',
      'you_are_offline': 'أنت غير متصل',
      'toggle_availability_desc': 'قم بتغيير حالتك للبدء في استلام عروض العمل',
      'no_jobs_nearby': 'لا توجد وظائف متاحة في مكان قريب',
      'new_jobs_desc': 'ستظهر الوظائف الجديدة هنا تلقائياً',
      'no_orders_nearby': 'لا توجد طلبات قريبة',
      'pull_to_refresh_desc': 'اسحب للتحديث أو انتظر طلبات جديدة',
      'delivery_details': 'تفاصيل التوصيل',
      'order_information': 'معلومات الطلب',
      'locations': 'المواقع',
      'delivery_fee': 'رسوم التوصيل',
      'delivery_accepted': 'تم قبول التوصيل!',
      'failed_to_accept': 'فشل قبول التوصيل',
      'head_to_pharmacy': 'توجه إلى الصيدلية',
      'head_to_patient': 'توجه إلى المريض',
      'delivery_complete': 'اكتمل التوصيل!',
      'complete_delivery_before_back': 'أكمل التوصيل قبل العودة',
      'pickup_location': 'موقع الاستلام',
      'delivery_location': 'موقع التوصيل',
      'then_deliver_to': 'ثم قم بالتوصيل إلى',
      'completed': 'مكتمل',
      'delivery_done': 'تم التوصيل بنجاح',
      'arrived_at_pharmacy': 'وصلت إلى الصيدلية',
      'arrived_at_patient': 'وصلت إلى المريض',
      'you_earned': 'لقد ربحت',
      'back_to_home': 'العودة إلى الرئيسية',
      
      // Tasks
      'order_id': 'رقم الطلب',
      'pickup': 'الاستلام',
      'delivery': 'التوصيل',
      'accept_task': 'قبول المهمة',
      'reject_task': 'رفض المهمة',
      'start_pickup': 'بدء الاستلام',
      'mark_picked_up': 'تم الاستلام',
      'start_delivery': 'بدء التوصيل',
      'mark_delivered': 'تم التوصيل',
      'view_on_map': 'عرض على الخريطة',
      'call_customer': 'اتصال بالعميل',
      'call_pharmacy': 'اتصال بالصيدلية',
      
      // General
      'status': 'الحالة',
      'pending': 'معلق',
      'on_way': 'في الطريق',
      'delivered': 'تم التوصيل',
      'cancelled': 'تم الإلغاء',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'fr', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return Future.value(AppLocalizations(locale));
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
