import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Auth
      'login': 'Login',
      'register': 'Register',
      'welcome_back': 'Welcome Back',
      'login_to_pharmacy_account': 'Login to your pharmacy account',
      'phone_number': 'Phone Number',
      'phone_hint': 'e.g. +212600000000',
      'enter_phone': 'Please enter your phone number',
      'include_country_code': 'Include country code (e.g. +212)',
      'resend': 'Resend',
      'send_otp': 'Send OTP',
      'otp_sent_success': 'OTP sent successfully',
      'failed_send_otp': 'Failed to send OTP',
      'enter_otp': 'Enter OTP',
      'otp_hint': 'Enter the OTP sent to your phone',
      'please_enter_otp': 'Please enter the OTP',
      'login_failed': 'Login failed',
      'no_account_register': "Don't have an account? Register",
      'register_pharmacy': 'Register Pharmacy',
      'create_pharmacy_account': 'Create Pharmacy Account',
      'pharmacy_name': 'Pharmacy Name',
      'license_number': 'License Number',
      'pharmacy_address': 'Pharmacy Address',
      'select_location_map': 'Select Location on Map',
      'change_location_map': 'Change Location on Map',
      'location_selected': 'Location selected',
      'send_otp_continue': 'Send OTP & Continue',
      'already_have_account_login': 'Already have an account? Login',
      'please_select_location': 'Please select location on map',
      'required': 'Required',
      'min_6_chars': 'Min 6 characters',
      'verify_phone': 'Verify Phone',
      'verify_your_phone': 'Verify Your Phone',
      'sent_code_to': 'We sent a 6-digit code to',
      'verify_register': 'Verify & Register',
      'didnt_receive_code': "Didn't receive code?",
      'resend_in': 'Resend in',
      'registration_submitted': 'Registration Submitted!',
      'pharmacy_under_review': 'Your pharmacy registration is under review by our admin team.',
      'approval_time': 'Approval takes 24 to 48 hours.',
      'ok_got_it': 'OK, Got it',
      'enter_6_digit_otp': 'Please enter the 6-digit OTP',
      'something_went_wrong': 'Something went wrong',
      'waiting_admin_approval': 'Waiting for Admin Approval',
      'pharmacy_submitted_desc': 'Your pharmacy registration has been submitted. Our admin team will review your details and license.',
      'approval_takes_time': 'Approval typically takes 24 to 48 hours.',
      'check_status': 'Check Status',
      'checking': 'Checking...',
      'still_pending': 'Still pending approval. Please wait.',
      'application_rejected': 'Application Rejected',
      'pharmacy_rejected_desc': 'Unfortunately, your pharmacy registration was not approved by the admin.',
      'admin_note': 'Admin Note',
      'try_again': 'Try Again',
      'otp_resent_success': 'OTP resent to your phone',

      // Profile
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'wallet': 'Wallet',
      'pharmacy_info': 'Pharmacy Info',
      'change_password': 'Change Password',
      'help_support': 'Help & Support',
      'logout': 'Logout',
      'language': 'Language',
      'select_language': 'Select Language',
      'english': 'English',
      'french': 'French',
      'arabic': 'Arabic',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'full_name': 'Full Name',
      'phone': 'Phone',
      'save_changes': 'Save Changes',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'update_password': 'Update Password',
      'logout_confirm': 'Are you sure you want to logout?',
      'payment_settings': 'Payment Settings',
      'add_payment_method': 'Add Payment Method',
      'edit_payment_method': 'Edit Payment Method',
      'payment_method_name': 'Method Name (e.g. UPI, Bank)',
      'payment_details': 'Payment Details (e.g. ID, Number)',
      'no_payment_methods': 'No payment methods added',
      'delete_payment_confirm': 'Delete this payment method?',

      // Dashboard & Navigation
      'dashboard': 'Dashboard',
      'requests': 'Requests',
      'orders': 'Orders',
      'total_sales': 'Total Sales',
      'active_requests': 'Active Requests',
      'pending_orders': 'Pending Orders',
      'completed_orders': 'Completed Orders',
      'recent_activity': 'Recent Activity',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'rider_assigned': 'Rider Assigned',
      'view_all': 'View All',
      'respond_quickly': 'Respond Quickly',
      'respond_quickly_desc': 'Faster quote responses increase your order acceptance rate.',
      
      // Requests Screen
      'new_requests': 'New Requests',
      'no_requests': 'No pending requests',
      'distance': 'Distance',
      'view_details': 'View Details',
      'send_quote': 'Send Quote',
      'reject': 'Reject',
      'accept': 'Accept',
      'medicine_name': 'Medicine Name',
      'quantity': 'Quantity',
      'add_medicine': 'Add Medicine',
      'subtotal': 'Subtotal',
      'delivery_fee': 'Delivery Fee',
      'total': 'Total',
      
      // Orders Screen
      'order_id': 'Order ID',
      'customer': 'Customer',
      'status': 'Status',
      'preparing': 'Preparing',
      'ready_for_pickup': 'Ready for Pickup',
      'picked_up': 'Picked Up',
      'on_the_way': 'On the Way',
      'delivered': 'Delivered',
      'cancelled': 'Cancelled',
      'update_status': 'Update Status',
      'prescription_requests': 'Prescription Requests',
      'retry': 'Retry',
      'no_requests_yet': 'No Requests Yet',
      'no_orders_yet': 'No Orders Yet',
      'confirmed_orders_desc': 'Confirmed orders will appear here',
      'order_history': 'Order History',
      'item': 'item',
      'items': 'items',
      'mad': 'MAD',
      'view_edit_quote': 'View & Edit Quote',
      'view_send_quote': 'View & Send Quote',
      'order_confirmed_by_patient': '✓ Order Confirmed by Patient',
      'reject_prescription': 'Reject Prescription',
      'reject_desc': 'Please provide a reason for rejection.',
      'reject_reassign': 'Reject & Reassign',
      'rejecting': 'Rejecting...',
      'minutes_ago': 'm ago',
      'hours_ago': 'h ago',
      'days_ago': 'd ago',
    },
    'fr': {
      // Auth
      'login': 'Connexion',
      'register': 'S\'inscrire',
      'welcome_back': 'Bon retour',
      'login_to_pharmacy_account': 'Connectez-vous à votre compte pharmacie',
      'phone_number': 'Numéro de téléphone',
      'phone_hint': 'ex: +212600000000',
      'enter_phone': 'Veuillez entrer votre numéro de téléphone',
      'include_country_code': 'Inclure le code pays (ex: +212)',
      'resend': 'Renvoyer',
      'send_otp': 'Envoyer l\'OTP',
      'otp_sent_success': 'OTP envoyé avec succès',
      'failed_send_otp': 'Échec de l\'envoi de l\'OTP',
      'enter_otp': 'Entrer l\'OTP',
      'otp_hint': 'Entrez l\'OTP envoyé à votre téléphone',
      'please_enter_otp': 'Veuillez entrer l\'OTP',
      'login_failed': 'Échec de la connexion',
      'no_account_register': 'Pas de compte ? S\'inscrire',
      'register_pharmacy': 'Inscrire une pharmacie',
      'create_pharmacy_account': 'Créer un compte pharmacie',
      'pharmacy_name': 'Nom de la pharmacie',
      'license_number': 'Numéro de licence',
      'pharmacy_address': 'Adresse de la pharmacie',
      'select_location_map': 'Sélectionner l\'emplacement sur la carte',
      'change_location_map': 'Modifier l\'emplacement sur la carte',
      'location_selected': 'Emplacement sélectionné',
      'send_otp_continue': 'Envoyer l\'OTP et continuer',
      'already_have_account_login': 'Déjà un compte ? Se connecter',
      'please_select_location': 'Veuillez sélectionner l\'emplacement sur la carte',
      'required': 'Requis',
      'min_6_chars': 'Min 6 caractères',
      'verify_phone': 'Vérifier le téléphone',
      'verify_your_phone': 'Vérifiez votre téléphone',
      'sent_code_to': 'Nous avons envoyé un code à 6 chiffres à',
      'verify_register': 'Vérifier et s\'inscrire',
      'didnt_receive_code': 'Pas reçu le code ?',
      'resend_in': 'Renvoyer dans',
      'registration_submitted': 'Inscription soumise !',
      'pharmacy_under_review': 'Votre inscription de pharmacie est en cours de révision par notre équipe.',
      'approval_time': 'L\'approbation prend 24 à 48 heures.',
      'ok_got_it': 'OK, j\'ai compris',
      'enter_6_digit_otp': 'Veuillez entrer le code à 6 chiffres',
      'something_went_wrong': 'Quelque chose s\'est mal passé',
      'waiting_admin_approval': 'En attente d\'approbation',
      'pharmacy_submitted_desc': 'Votre inscription de pharmacie a été soumise. Notre équipe examinera vos détails et votre licence.',
      'approval_takes_time': 'L\'approbation prend généralement 24 à 48 heures.',
      'check_status': 'Vérifier le statut',
      'checking': 'Vérification...',
      'still_pending': 'Toujours en attente d\'approbation. Veuillez patienter.',
      'application_rejected': 'Demande rejetée',
      'pharmacy_rejected_desc': 'Malheureusement, votre inscription de pharmacie n\'a pas été approuvée.',
      'admin_note': 'Note de l\'admin',
      'try_again': 'Réessayer',
      'otp_resent_success': 'OTP renvoyé sur votre téléphone',

      // Profile
      'profile': 'Profil',
      'edit_profile': 'Modifier le profil',
      'wallet': 'Portefeuille',
      'pharmacy_info': 'Infos Pharmacie',
      'change_password': 'Modifier le mot de passe',
      'help_support': 'Aide et support',
      'logout': 'Déconnexion',
      'language': 'Langue',
      'select_language': 'Choisir la langue',
      'english': 'Anglais',
      'french': 'Français',
      'arabic': 'Arabe',
      'confirm': 'Confirmer',
      'cancel': 'Annuler',
      'full_name': 'Nom complet',
      'phone': 'Téléphone',
      'save_changes': 'Enregistrer les modifications',
      'current_password': 'Mot de passe actuel',
      'new_password': 'Nouveau mot de passe',
      'update_password': 'Mettre à jour le mot de passe',
      'logout_confirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
      'payment_settings': 'Paramètres de paiement',
      'add_payment_method': 'Ajouter un mode de paiement',
      'edit_payment_method': 'Modifier le mode de paiement',
      'payment_method_name': 'Nom de la méthode (ex: UPI, Banque)',
      'payment_details': 'Détails du paiement (ex: ID, Numéro)',
      'no_payment_methods': 'Aucun mode de paiement ajouté',
      'delete_payment_confirm': 'Supprimer ce mode de paiement ?',

      // Dashboard & Navigation
      'dashboard': 'Tableau de bord',
      'requests': 'Demandes',
      'orders': 'Commandes',
      'total_sales': 'Ventes totales',
      'active_requests': 'Demandes actives',
      'pending_orders': 'Commandes en attente',
      'completed_orders': 'Commandes terminées',
      'recent_activity': 'Activité récente',
      'good_morning': 'Bonjour',
      'good_afternoon': 'Bon après-midi',
      'good_evening': 'Bonsoir',
      'rider_assigned': 'Livreur assigné',
      'view_all': 'Voir tout',
      'respond_quickly': 'Répondez rapidement',
      'respond_quickly_desc': 'Des réponses rapides aux devis augmentent votre taux d\'acceptation.',
      
      // Requests Screen
      'new_requests': 'Nouvelles demandes',
      'no_requests': 'Aucune demande en attente',
      'distance': 'Distance',
      'view_details': 'Voir les détails',
      'send_quote': 'Envoyer un devis',
      'reject': 'Rejeter',
      'accept': 'Accepter',
      'medicine_name': 'Nom du médicament',
      'quantity': 'Quantité',
      'add_medicine': 'Ajouter un médicament',
      'subtotal': 'Sous-total',
      'delivery_fee': 'Frais de livraison',
      'total': 'Total',
      
      // Orders Screen
      'order_id': 'ID de commande',
      'customer': 'Client',
      'status': 'Statut',
      'preparing': 'En préparation',
      'ready_for_pickup': 'Prêt pour le ramassage',
      'picked_up': 'Récupéré',
      'on_the_way': 'En chemin',
      'delivered': 'Livré',
      'cancelled': 'Annulé',
      'update_status': 'Mettre à jour le statut',
      'prescription_requests': 'Demandes d\'ordonnance',
      'retry': 'Réessayer',
      'no_requests_yet': 'Pas encore de demandes',
      'no_orders_yet': 'Pas encore de commandes',
      'confirmed_orders_desc': 'Les commandes confirmées apparaîtront ici',
      'order_history': 'Historique des commandes',
      'item': 'article',
      'items': 'articles',
      'mad': 'DH',
      'view_edit_quote': 'Voir et modifier le devis',
      'view_send_quote': 'Voir et envoyer le devis',
      'order_confirmed_by_patient': '✓ Commande confirmée par le patient',
      'reject_prescription': 'Rejeter l\'ordonnance',
      'reject_desc': 'Veuillez fournir un motif de rejet.',
      'reject_reassign': 'Rejeter et réassigner',
      'rejecting': 'Rejet en cours...',
      'minutes_ago': 'il y a m min',
      'hours_ago': 'il y a h h',
      'days_ago': 'il y a d j',
    },
    'ar': {
      // Auth
      'login': 'تسجيل الدخول',
      'register': 'تسجيل',
      'welcome_back': 'مرحباً بك',
      'login_to_pharmacy_account': 'تسجيل الدخول إلى حساب الصيدلية الخاص بك',
      'phone_number': 'رقم الهاتف',
      'phone_hint': 'مثال: +212600000000',
      'enter_phone': 'يرجى إدخال رقم هاتفك',
      'include_country_code': 'تضمين رمز الدولة (مثال: +212)',
      'resend': 'إعادة إرسال',
      'send_otp': 'إرسال رمز التحقق',
      'otp_sent_success': 'تم إرسال رمز التحقق بنجاح',
      'failed_send_otp': 'فشل إرسال رمز التحقق',
      'enter_otp': 'أدخل رمز التحقق',
      'otp_hint': 'أدخل رمز التحقق المرسل إلى هاتفك',
      'please_enter_otp': 'يرجى إدخال رمز التحقق',
      'login_failed': 'فشل تسجيل الدخول',
      'no_account_register': 'ليس لديك حساب؟ سجل الآن',
      'register_pharmacy': 'تسجيل صيدلية',
      'create_pharmacy_account': 'إنشاء حساب صيدلية',
      'pharmacy_name': 'اسم الصيدلية',
      'license_number': 'رقم الرخصة',
      'pharmacy_address': 'عنوان الصيدلية',
      'select_location_map': 'اختر الموقع على الخريطة',
      'change_location_map': 'تغيير الموقع على الخريطة',
      'location_selected': 'تم اختيار الموقع',
      'send_otp_continue': 'إرسال رمز التحقق والمتابعة',
      'already_have_account_login': 'لديك حساب بالفعل؟ تسجيل الدخول',
      'please_select_location': 'يرجى اختيار الموقع على الخريطة',
      'required': 'مطلوب',
      'min_6_chars': '6 أحرف على الأقل',
      'verify_phone': 'تأكيد الهاتف',
      'verify_your_phone': 'أكد رقم هاتفك',
      'sent_code_to': 'لقد أرسلنا رمزاً مكوناً من 6 أرقام إلى',
      'verify_register': 'تأكيد وتسجيل',
      'didnt_receive_code': 'لم يصلك الرمز؟',
      'resend_in': 'إعادة الإرسال خلال',
      'registration_submitted': 'تم تقديم الطلب!',
      'pharmacy_under_review': 'طلب تسجيل الصيدلية الخاص بك قيد المراجعة من قبل فريقنا.',
      'approval_time': 'الموافقة تستغرق من 24 إلى 48 ساعة.',
      'ok_got_it': 'حسناً، فهمت',
      'enter_6_digit_otp': 'يرجى إدخال الرمز المكون من 6 أرقام',
      'something_went_wrong': 'حدث خطأ ما',
      'waiting_admin_approval': 'في انتظار موافقة المسؤول',
      'pharmacy_submitted_desc': 'تم تقديم طلب تسجيل الصيدلية الخاص بك. سيقوم فريقنا بمراجعة بياناتك والترخيص.',
      'approval_takes_time': 'تستغرق الموافقة عادةً من 24 إلى 48 ساعة.',
      'check_status': 'التحقق من الحالة',
      'checking': 'جاري التحقق...',
      'still_pending': 'لا يزال الطلب قيد المراجعة. يرجى الانتظار.',
      'application_rejected': 'تم رفض الطلب',
      'pharmacy_rejected_desc': 'للأسف، لم يتمت الموافقة على طلب تسجيل الصيدلية الخاص بك.',
      'admin_note': 'ملاحظة المسؤول',
      'try_again': 'حاول مرة أخرى',
      'otp_resent_success': 'تم إعادة إرسال رمز التحقق إلى هاتفك',

      // Profile
      'profile': 'الملف الشخصي',
      'edit_profile': 'تعديل الملف الشخصي',
      'wallet': 'المحفظة',
      'pharmacy_info': 'معلومات الصيدلية',
      'change_password': 'تغيير كلمة المرور',
      'help_support': 'المساعدة والدعم',
      'logout': 'تسجيل الخروج',
      'language': 'اللغة',
      'select_language': 'اختر اللغة',
      'english': 'الإنجليزية',
      'french': 'الفرنسية',
      'arabic': 'العربية',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'full_name': 'الاسم الكامل',
      'phone': 'الهاتف',
      'save_changes': 'حفظ التغييرات',
      'current_password': 'كلمة المرور الحالية',
      'new_password': 'كلمة المرور الجديدة',
      'update_password': 'تحديث كلمة المرور',
      'logout_confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'payment_settings': 'إعدادات الدفع',
      'add_payment_method': 'إضافة طريقة دفع',
      'edit_payment_method': 'تعديل طريقة الدفع',
      'payment_method_name': 'اسم الطريقة (مثال: UPI، بنك)',
      'payment_details': 'تفاصيل الدفع (مثال: معرف، رقم)',
      'no_payment_methods': 'لم يتم إضافة طرق دفع',
      'delete_payment_confirm': 'هل تريد حذف طريقة الدفع هذه؟',

      // Dashboard & Navigation
      'dashboard': 'لوحة التحكم',
      'requests': 'الطلبات',
      'orders': 'الطلبيات',
      'total_sales': 'إجمالي المبيعات',
      'active_requests': 'الطلبات النشطة',
      'pending_orders': 'الطلبات المعلقة',
      'completed_orders': 'الطلبات المكتملة',
      'recent_activity': 'النشاط الأخير',
      'good_morning': 'صباح الخير',
      'good_afternoon': 'مساء الخير',
      'good_evening': 'مساء الخير',
      'rider_assigned': 'تم تعيين سائق',
      'view_all': 'عرض الكل',
      'respond_quickly': 'استجب بسرعة',
      'respond_quickly_desc': 'الرد السريع على عروض الأسعار يزيد من معدل قبول طلباتك.',
      
      // Requests Screen
      'new_requests': 'طلبات جديدة',
      'no_requests': 'لا توجد طلبات معلقة',
      'distance': 'المسافة',
      'view_details': 'عرض التفاصيل',
      'send_quote': 'إرسال عرض سعر',
      'reject': 'رفض',
      'accept': 'قبول',
      'medicine_name': 'اسم الدواء',
      'quantity': 'الكمية',
      'add_medicine': 'إضافة دواء',
      'subtotal': 'المجموع الفرعي',
      'delivery_fee': 'رسوم التوصيل',
      'total': 'الإجمالي',
      
      // Orders Screen
      'order_id': 'رقم الطلب',
      'customer': 'العميل',
      'status': 'الحالة',
      'preparing': 'جاري التحضير',
      'ready_for_pickup': 'جاهز للاستلام',
      'picked_up': 'تم الاستلام',
      'on_the_way': 'في الطريق',
      'delivered': 'تم التوصيل',
      'cancelled': 'تم الإلغاء',
      'update_status': 'تحديث الحالة',
      'prescription_requests': 'طلبات الوصفات الطبية',
      'retry': 'إعادة المحاولة',
      'no_requests_yet': 'لا توجد طلبات بعد',
      'no_orders_yet': 'لا توجد طلبيات بعد',
      'confirmed_orders_desc': 'ستظهر الطلبيات المؤكدة هنا',
      'order_history': 'سجل الطلبيات',
      'item': 'عنصر',
      'items': 'عناصر',
      'mad': 'درهم',
      'view_edit_quote': 'عرض وتعديل عرض السعر',
      'view_send_quote': 'عرض وإرسال عرض السعر',
      'order_confirmed_by_patient': '✓ تم تأكيد الطلب من قبل المريض',
      'reject_prescription': 'رفض الوصفة الطبية',
      'reject_desc': 'يرجى تقديم سبب للرفض.',
      'reject_reassign': 'رفض وإعادة التعيين',
      'rejecting': 'جاري الرفض...',
      'minutes_ago': 'منذ م دقيقة',
      'hours_ago': 'منذ ح ساعة',
      'days_ago': 'منذ د يوم',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'fr', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return Future.value(AppLocalizations(locale));
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
