import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Profile
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'wallet': 'Wallet',
      'pharmacy_info': 'Pharmacy Info',
      'change_password': 'Change Password',
      'help_support': 'Help & Support',
      'logout': 'Logout',
      'language': 'Language',
      'select_language': 'Select Language',
      'english': 'English',
      'french': 'French',
      'arabic': 'Arabic',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'saved_addresses': 'Saved Addresses',
      'payment_methods': 'Payment Methods',
      'notifications': 'Notifications',
      'about': 'About',
      'logout_confirm': 'Are you sure you want to logout?',
      'delete_account': 'Delete Account',
      'delete': 'Delete',
      'delete_account_confirm': 'This will permanently delete your account and all your data. This action cannot be undone. Are you sure?',
      'account_deleted': 'Your account has been deleted',
      'delete_account_failed': 'Failed to delete account',
      
      // Home & General
      'home': 'Home',
      'welcome_back': 'Welcome back,',
      'how_can_we_help': 'How can we help you today?',
      'upload_prescription': 'Upload Prescription',
      'order_history': 'Order History',
      'my_quotes': 'My Quotes',
      'active_orders': 'Active Orders',
      'view_all': 'View All',
      'no_active_orders': 'No active orders',
      'search_pharmacies': 'Search pharmacies...',
      
      // Prescription Upload
      'select_prescription': 'Select Prescription',
      'take_photo': 'Take a Photo',
      'choose_gallery': 'Choose from Gallery',
      'prescription_desc': 'Please ensure the prescription is clear and readable.',
      'upload_now': 'Upload Now',
      'uploading': 'Uploading...',
      'success': 'Success',
      'error': 'Error',
      'prescription_uploaded': 'Prescription uploaded successfully!',
      
      // Quotes & Orders
      'order_details': 'Order Details',
      'quote_received': 'Quote Received!',
      'order_information': 'Order Information',
      'requested_medicines': 'Requested Medicines',
      'quote_details': 'Quote Details',
      'total': 'Total',
      'subtotal': 'Subtotal',
      'service_fee': 'Service Fee',
      'delivery_fee': 'Delivery Fee',
      'pay_now': 'Pay Now',
      'confirm_order': 'Confirm Order',
      'status': 'Status',
      'order_placed': 'Order Placed',
      'payment_verification': 'Payment Verification',
      'searching_pharmacy': 'Searching for Pharmacy...',
      'no_pharmacy_found': 'No pharmacy found nearby',
      'order_confirmed': 'Order Confirmed',
      'order_preparing': 'Preparing Medicines',
      'order_ready': 'Ready for Pickup',
      'order_picked_up': 'Picked Up',
      'order_on_way': 'On the Way',
      'order_delivered': 'Delivered',
      'order_cancelled': 'Cancelled',
      'order_expired': 'Request Expired',
      
      // Tracking
      'track_order': 'Track Order',
      'rider_info': 'Delivery Rider',
      'est_delivery': 'Est. Delivery',
      'address': 'Address',
      'order_not_found': 'Order not found',
      'retry': 'Retry',
      'finding_pharmacy_desc': 'Looking for the nearest pharmacy...',
      'no_pharmacy_timeout': 'No pharmacy responded within the 1-hour limit.',
      'pharmacy_quote': 'Pharmacy Quote',
      'medicine_breakdown': 'Medicine Breakdown',
      'decline': 'Decline',
      'accept': 'Accept',
      'cod': 'COD',
      'confirm_order_desc': 'Confirm this order for',
      'quote_cancelled_success': 'Quote cancelled. Request sent to next pharmacy!',
      'quote_cancelled_generic': 'Quote cancelled.',
      'confirming_order': 'Confirming order...',
      'payment_success': 'Payment successful! Order confirmed 🎉',
      'payment_failed': 'Payment failed',
      'no_quotes_yet': 'No quotes yet',
      'no_quotes_desc': 'Quotes from pharmacies will appear here',
      'more_items': 'more items...',
      'expires_in': 'Expires in',
      'quote_expires_in': 'Quote expires in',
      'expired': 'Expired',
      'minutes': 'minutes',
      'hours': 'hours',
    },
    'fr': {
      // Profile
      'profile': 'Profil',
      'edit_profile': 'Modifier le profil',
      'wallet': 'Portefeuille',
      'pharmacy_info': 'Infos Pharmacie',
      'change_password': 'Modifier le mot de passe',
      'help_support': 'Aide et support',
      'logout': 'Déconnexion',
      'language': 'Langue',
      'select_language': 'Choisir la langue',
      'english': 'Anglais',
      'french': 'Français',
      'arabic': 'Arabe',
      'confirm': 'Confirmer',
      'cancel': 'Annuler',
      'saved_addresses': 'Adresses enregistrées',
      'payment_methods': 'Moyens de paiement',
      'notifications': 'Notifications',
      'about': 'À propos',
      'logout_confirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
      'delete_account': 'Supprimer le compte',
      'delete': 'Supprimer',
      'delete_account_confirm': 'Cela supprimera définitivement votre compte et toutes vos données. Cette action est irréversible. Êtes-vous sûr ?',
      'account_deleted': 'Votre compte a été supprimé',
      'delete_account_failed': 'Échec de la suppression du compte',
      
      // Home & General
      'home': 'Accueil',
      'welcome_back': 'Bon retour,',
      'how_can_we_help': 'Comment pouvons-nous vous aider aujourd\'hui ?',
      'upload_prescription': 'Télécharger l\'ordonnance',
      'order_history': 'Historique des commandes',
      'my_quotes': 'Mes devis',
      'active_orders': 'Commandes actives',
      'view_all': 'Voir tout',
      'no_active_orders': 'Aucune commande active',
      'search_pharmacies': 'Rechercher des pharmacies...',
      
      // Prescription Upload
      'select_prescription': 'Sélectionner l\'ordonnance',
      'take_photo': 'Prendre une photo',
      'choose_gallery': 'Choisir dans la galerie',
      'prescription_desc': 'Veuillez vous assurer que l\'ordonnance est claire et lisible.',
      'upload_now': 'Télécharger maintenant',
      'uploading': 'Téléchargement...',
      'success': 'Succès',
      'error': 'Erreur',
      'prescription_uploaded': 'Ordonnance téléchargée avec succès !',
      
      // Quotes & Orders
      'order_details': 'Détails de la commande',
      'quote_received': 'Devis reçu !',
      'order_information': 'Informations sur la commande',
      'requested_medicines': 'Médicaments demandés',
      'quote_details': 'Détails du devis',
      'total': 'Total',
      'subtotal': 'Sous-total',
      'service_fee': 'Frais de service',
      'delivery_fee': 'Frais de livraison',
      'pay_now': 'Payer maintenant',
      'confirm_order': 'Confirmer la commande',
      'status': 'Statut',
      'order_placed': 'Commande passée',
      'payment_verification': 'Vérification du paiement',
      'searching_pharmacy': 'Recherche de pharmacie...',
      'no_pharmacy_found': 'Aucune pharmacie trouvée à proximité',
      'order_confirmed': 'Commande confirmée',
      'order_preparing': 'Préparation des médicaments',
      'order_ready': 'Prêt pour le ramassage',
      'order_picked_up': 'Récupéré',
      'order_on_way': 'En chemin',
      'order_delivered': 'Livré',
      'order_cancelled': 'Annulé',
      'order_expired': 'Demande expirée',
      
      // Tracking
      'track_order': 'Suivre la commande',
      'rider_info': 'Livreur',
      'est_delivery': 'Livraison prévue',
      'address': 'Adresse',
      'order_not_found': 'Commande introuvable',
      'retry': 'Réessayer',
      'finding_pharmacy_desc': 'Recherche de la pharmacie la plus proche...',
      'no_pharmacy_timeout': 'Aucune pharmacie n\'a répondu dans le délai d\'une heure.',
      'pharmacy_quote': 'Devis de la pharmacie',
      'medicine_breakdown': 'Détail des médicaments',
      'decline': 'Refuser',
      'accept': 'Accepter',
      'cod': 'Paiement à la livraison',
      'confirm_order_desc': 'Confirmer cette commande pour',
      'quote_cancelled_success': 'Devis annulé. Demande envoyée à la pharmacie suivante !',
      'quote_cancelled_generic': 'Devis annulé.',
      'confirming_order': 'Confirmation de la commande...',
      'payment_success': 'Paiement réussi ! Commande confirmée 🎉',
      'payment_failed': 'Échec du paiement',
      'no_quotes_yet': 'Pas encore de devis',
      'no_quotes_desc': 'Les devis des pharmacies apparaîtront ici',
      'more_items': 'articles supplémentaires...',
      'expires_in': 'Expire dans',
      'quote_expires_in': 'Le devis expire dans',
      'expired': 'Expiré',
      'minutes': 'minutes',
      'hours': 'heures',
    },
    'ar': {
      // Profile
      'profile': 'الملف الشخصي',
      'edit_profile': 'تعديل الملف الشخصي',
      'wallet': 'المحفظة',
      'pharmacy_info': 'معلومات الصيدلية',
      'change_password': 'تغيير كلمة المرور',
      'help_support': 'المساعدة والدعم',
      'logout': 'تسجيل الخروج',
      'language': 'اللغة',
      'select_language': 'اختر اللغة',
      'english': 'الإنجليزية',
      'french': 'الفرنسية',
      'arabic': 'العربية',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'saved_addresses': 'العناوين المحفوظة',
      'payment_methods': 'طرق الدفع',
      'notifications': 'التنبيهات',
      'about': 'حول',
      'logout_confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'delete_account': 'حذف الحساب',
      'delete': 'حذف',
      'delete_account_confirm': 'سيؤدي هذا إلى حذف حسابك وجميع بياناتك نهائيًا. لا يمكن التراجع عن هذا الإجراء. هل أنت متأكد؟',
      'account_deleted': 'تم حذف حسابك',
      'delete_account_failed': 'فشل حذف الحساب',
      
      // Home & General
      'home': 'الرئيسية',
      'welcome_back': 'مرحباً بك،',
      'how_can_we_help': 'كيف يمكننا مساعدتك اليوم؟',
      'upload_prescription': 'رفع الوصفة الطبية',
      'order_history': 'سجل الطلبات',
      'my_quotes': 'عروضي',
      'active_orders': 'الطلبات النشطة',
      'view_all': 'عرض الكل',
      'no_active_orders': 'لا توجد طلبات نشطة',
      'search_pharmacies': 'البحث عن صيدليات...',
      
      // Prescription Upload
      'select_prescription': 'اختر الوصفة الطبية',
      'take_photo': 'التقاط صورة',
      'choose_gallery': 'اختر من المعرض',
      'prescription_desc': 'يرجى التأكد من أن الوصفة واضحة ومقروءة.',
      'upload_now': 'رفع الآن',
      'uploading': 'جاري الرفع...',
      'success': 'تم بنجاح',
      'error': 'خطأ',
      'prescription_uploaded': 'تم رفع الوصفة بنجاح!',
      
      // Quotes & Orders
      'order_details': 'تفاصيل الطلب',
      'quote_received': 'تم استلام العرض!',
      'order_information': 'معلومات الطلب',
      'requested_medicines': 'الأدوية المطلوبة',
      'quote_details': 'تفاصيل العرض',
      'total': 'الإجمالي',
      'subtotal': 'المجموع الفرعي',
      'service_fee': 'رسوم الخدمة',
      'delivery_fee': 'رسوم التوصيل',
      'pay_now': 'ادفع الآن',
      'confirm_order': 'تأكيد الطلب',
      'status': 'الحالة',
      'order_placed': 'تم تقديم الطلب',
      'payment_verification': 'التحقق من الدفع',
      'searching_pharmacy': 'جاري البحث عن صيدلية...',
      'no_pharmacy_found': 'لم يتم العثور على صيدلية قريبة',
      'order_confirmed': 'تم تأكيد الطلب',
      'order_preparing': 'جاري تحضير الأدوية',
      'order_ready': 'جاهز للاستلام',
      'order_picked_up': 'تم الاستلام',
      'order_on_way': 'في الطريق',
      'order_delivered': 'تم التوصيل',
      'order_cancelled': 'تم الإلغاء',
      'order_expired': 'انتهت صلاحية الطلب',
      
      // Tracking
      'track_order': 'تتبع الطلب',
      'rider_info': 'مندوب التوصيل',
      'est_delivery': 'وقت التوصيل المتوقع',
      'address': 'العنوان',
      'order_not_found': 'الطلب غير موجود',
      'retry': 'إعادة المحاولة',
      'finding_pharmacy_desc': 'جاري البحث عن أقرب صيدلية...',
      'no_pharmacy_timeout': 'لم تستجب أي صيدلية خلال مهلة الساعة الواحدة.',
      'pharmacy_quote': 'عرض سعر الصيدلية',
      'medicine_breakdown': 'تفاصيل الأدوية',
      'decline': 'رفض',
      'accept': 'قبول',
      'cod': 'الدفع عند الاستلام',
      'confirm_order_desc': 'تأكيد هذا الطلب لـ',
      'quote_cancelled_success': 'تم إلغاء العرض. تم إرسال الطلب إلى الصيدلية التالية!',
      'quote_cancelled_generic': 'تم إلغاء العرض.',
      'confirming_order': 'جاري تأكيد الطلب...',
      'payment_success': 'تم الدفع بنجاح! تم تأكيد الطلب 🎉',
      'payment_failed': 'فشل عملية الدفع',
      'no_quotes_yet': 'لا توجد عروض أسعار بعد',
      'no_quotes_desc': 'ستظهر عروض أسعار الصيدليات هنا',
      'more_items': 'أصناف إضافية...',
      'expires_in': 'ينتهي خلال',
      'quote_expires_in': 'ينتهي عرض السعر خلال',
      'expired': 'منتهي الصلاحية',
      'minutes': 'دقيقة',
      'hours': 'ساعة',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'fr', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return Future.value(AppLocalizations(locale));
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
